name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Get dependencies
        working-directory: ./mobile
        run: flutter pub get

      - name: Build APK
        working-directory: ./mobile
        run: flutter build apk --release

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: mobile/build/app/outputs/flutter-app-release.apk
          tag_name: release-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
